FROM vault:0.9.3

LABEL maintainer   "Samsung SDS - J. Conner <snafu.x@gmail.com>"
LABEL purpose      "Hashicorp Vault container build for Samsung SDS auto-init chart"

# Set up base tools
RUN apk add --no-cache curl jq 